apiVersion: v1
kind: Reaction
name: alerts-slack
spec:
  kind: Http
  properties:
    baseUrl:
      kind: Secret
      name: slack-webhook
      key: slack-webhook-url
    timeout: 30000

  queries:
    risky-containers: >
      added:
        method: "POST"
        url: ""
        headers:
          "Content-Type": "application/json"
        body: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "🚨 Risky Container Detected"
                }
              },
              {
                "type": "section",
                "fields": [
                  { "type": "mrkdwn", "text": "*Pod:*\n`{{after.pod}}`" },
                  { "type": "mrkdwn", "text": "*Namespace:*\n`{{after.namespace}}`" },
                  { "type": "mrkdwn", "text": "*Container:*\n`{{after.name}}`" },
                  { "type": "mrkdwn", "text": "*Image:*\n`{{after.image}}`" },
                  { "type": "mrkdwn", "text": "*Reason:*\n{{after.reason}}" },
                  { "type": "mrkdwn", "text": "*Mitigation:*\n{{after.mitigation}}" }
                ]
              }
            ]
          }

      deleted:
        method: "POST"
        url: ""
        headers:
          "Content-Type": "application/json"
        body: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "✅ Risky Container Resolved"
                }
              },
              {
                "type": "section",
                  "fields": [
                    { "type": "mrkdwn", "text": "*Pod:*\n`{{before.pod}}`" },
                    { "type": "mrkdwn", "text": "*Namespace:*\n`{{before.namespace}}`" },
                  { "type": "mrkdwn", "text": "*Container:*\n`{{before.name}}`" },
                  { "type": "mrkdwn", "text": "*Image:*\n`{{before.image}}`" }
                ]
              }
            ]
          }