apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: workflow-pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: "workflow-redis.default.svc.cluster.local:6379"
  - name: redisPassword
    value: ""
  - name: consumerID
    value: "workflow-service"
  - name: enableTLS
    value: "false"