kind: Reaction
apiVersion: v1
name: stock-notifications-publisher
spec:
  kind: PostDaprPubSub
  queries:
    # Publish low stock events to the inventory events topic
    low-stock-event-query: >
      {
        "pubsubName": "notifications-pubsub",
        "topicName": "drasi-events-low-stock-event-query",
        "format": "Unpacked",
        "skipControlSignals": true
      }
    
    # Publish critical stock events to the inventory events topic
    critical-stock-event-query: >
      {
        "pubsubName": "notifications-pubsub",
        "topicName": "drasi-events-critical-stock-event-query",
        "format": "Unpacked",
        "skipControlSignals": true
      }