name: Draft Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version Tag'
        required: true
        default: 'default'      

jobs:
  getting_started:
    permissions:
      contents: write
      packages: read  
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Zip tutorial folder
        run: |
          zip -r quickstart-dev-container.zip tutorial/getting-started
      
      - name: Create GitHub Release
        run: |
          VERSION="${{ inputs.tag || 'latest' }}"
          gh release create $VERSION quickstart-dev-container.zip  --draft --title $VERSION